output_dir: "../Trainer/outputs/" # modify it
device: 'cpu' # you can change this device to cpu or cuda:0
dataset:
  root_dir: '../Dataset/cars_dataset/' # modify it
  augmentation: # you can add any augmemtation parameters in here
    rotation_range: 45
    sharpness_factor: 2
    distortion_scale: 0.5
    bits: 2
  
  train_dir: '../Dataset/cars_dataset/train/' # modify it
  val_dir: '../Dataset/cars_dataset/test/' # modify it
  test_dir: '../Dataset/cars_dataset/test/' # modify it
  
  mean: [0.485, 0.456, 0.406] # from imagenet
  std: [0.229, 0.224, 0.225] # from imagenet
  
  num_workers: 2
  
model:
  backbone: 'inception_v3' # name of backbone or network models
  weights: 'IMAGENET1K_V1'
  # pretrained: true # will be deprecated on torch 0.15
  input_size: [224, 224]
  num_classes: 196

train:
  batch_size: 32 # num of batch size
  optimizer: 'adam'
  lr: 0.0001 # learning rate
  num_epochs: 20 # num of epoch

val:
  batch_size: 32

test:
  batch_size: 32

logger:
  api_key: "ZlKuBWBHA9epZ4XIGUkNnolj8" # private keys
  workspace: "wahyu-adi-n" # user-name
  project_name: "vehicle_attribute_recognition" # name  of project